import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "../components/Navbar/Navbar";
import { Footer } from "../components/Footer/Footer"
import { CartProvider } from "../components/CartContext/CartContext";
import { AuthProvider } from "../components/CartContext/AuthContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Panama es Cultura",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <CartProvider>
            <Navbar />
            {children}
            <Footer/>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
